<a href="https://colab.research.google.com/github/DevendraaK/Bangalore-House-Linear-Regression/blob/main/Fish_Catching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [39]:
from google.colab import files
data=files.upload()

Saving Fish.csv to Fish.csv


In [40]:
dataset=pd.read_csv('Fish.csv')
print(dataset)

      Species   Area Units  2013  2012  ...  2009  2008  2007  2006  2014
0         ANF   27.0   TLW  1633  1716  ...   853   964  1363  1193   993
1         ANF  274.0   TLW   137   133  ...   140   185   181   141   217
2         ANF  274.0   TLW     0     0  ...     0     0     0     0     0
3         ANF  274.0   TLW   135   131  ...   134   181   179   138   213
4         ANF  274.0   TLW     2     2  ...     6     4     3     3     4
...       ...    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...
49104     WHG  277.0   TLW     0     0  ...     0     0     0     0     1
49105     WHG  277.0   TLW     0     0  ...     0     0     0     0     1
49106     WRA   27.0   TLW     0     0  ...     0     0     0     0    14
49107     WRA  277.0   TLW     0     0  ...     0     0     0     0    14
49108     WRA  277.0   TLW     0     0  ...     0     0     0     0    14

[49109 rows x 12 columns]


In [41]:
X=dataset.iloc[:,1:-1].values
y = dataset.iloc[:, -1].values

In [42]:
# print(X)
print(y)

[993 217   0 ...  14  14  14]


In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [44]:
print(X)

[[27.0 0 1633 ... 964 1363 1193]
 [274.0 0 137 ... 185 181 141]
 [274.0 0 0 ... 0 0 0]
 ...
 [27.0 0 0 ... 0 0 0]
 [277.0 0 0 ... 0 0 0]
 [277.0 0 0 ... 0 0 0]]


In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [46]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [47]:
ann = tf.keras.models.Sequential()

In [48]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [49]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [50]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [51]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [52]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1228/1228 [==============================] - 3s 1ms/step - loss: -21474.6094 - accuracy: 0.0412
Epoch 2/100
1228/1228 [==============================] - 2s 1ms/step - loss: -351356.8125 - accuracy: 0.0398
Epoch 3/100
1228/1228 [==============================] - 1s 1ms/step - loss: -1088274.0000 - accuracy: 0.0398
Epoch 4/100
1228/1228 [==============================] - 1s 1ms/step - loss: -2247966.2500 - accuracy: 0.0398
Epoch 5/100
1228/1228 [==============================] - 2s 1ms/step - loss: -3878128.7500 - accuracy: 0.0398
Epoch 6/100
1228/1228 [==============================] - 1s 1ms/step - loss: -6306969.0000 - accuracy: 0.0398
Epoch 7/100
1228/1228 [==============================] - 2s 1ms/step - loss: -9603163.0000 - accuracy: 0.0398
Epoch 8/100
1228/1228 [==============================] - 1s 1ms/step - loss: -13686255.0000 - accuracy: 0.0398
Epoch 9/100
1228/1228 [==============================] - 1s 1ms/step - loss: -18892498.0000 - accuracy: 0.0398
Epoch 10/10

In [53]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[  1   0]
 [  1   0]
 [  1 231]
 ...
 [  1   0]
 [  1   0]
 [  1   0]]


In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[   0 7136    0 ...    0    0    0]
 [   0  387    0 ...    0    0    0]
 [   0  141    0 ...    0    0    0]
 ...
 [   0    1    0 ...    0    0    0]
 [   0    1    0 ...    0    0    0]
 [   0    1    0 ...    0    0    0]]


0.039401343921808184