<a href="https://colab.research.google.com/github/DevendraaK/Bangalore-House-Linear-Regression/blob/main/Tamil_tweets_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   #Importing the libraries
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
from google.colab import files
data=files.upload()

Saving TANGLISH.tsv to TANGLISH.tsv


In [4]:
data=pd.read_csv('TANGLISH.tsv',delimiter='\t')

In [5]:
print(data)

                                                   text  category
0      Daily likes & views pakka vanthavaga ellaruku...         1
1      25 k dislikes ethuku da intha trailerku poi a...         0
2                    #Lyca unna nenacha pavama iruku ya         0
3               It looks like Hindi movie amitab bachan         1
4      Thalaivarukku nejamavey vayasaagiduchu... siv...         1
...                                                 ...       ...
1255   Sappypathy Vijayamma bigilu ummpi get more di...         0
1256                     Stylea erukana ha ha naturally         1
1257              Style la irukana hahaha mass dialogue         0
1258   Like for lokesh kanagaraj THALAPATHY 64 Director         0
1259   Naa indha trailer 30 time paathuten pakka pak...         1

[1260 rows x 2 columns]


In [10]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer #stemming model is used for the process of stem eg if a sentence is "I loved this" in this case stem model will convert this to "loved" to "love",that will help us to predcting the result
corpus=[]#IT WILL CONTAIN CLEAN REVIEWS FROM THE DATASET
for i in range(0,1260):
  review=re.sub('[^a-zA-Z]',' ',data['text'][i] )  #remove all puntuation
  review=review.lower()
  review=review.split()
  ps=PorterStemmer()
  review=[ps.stem(word) for word in review if not word in set(stopwords.words('english')) ]
  review=' '.join(review)
  corpus.append(review)




[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
print(corpus)

['daili like view pakka vanthavaga ellarukum vanakkam', 'k dislik ethuku da intha trailerku poi apdi ungalukku entha trailer tha pidikum', 'lyca unna nenacha pavama iruku ya', 'look like hindi movi amitab bachan', 'thalaivarukku nejamavey vayasaagiduchu sivaji thalaivaroda peak', 'thala nu sollu thala nemirinthu nillu', 'pink origin version pathavikaluku trailer old maritha irukum pakathvigalukutha scene um new ah irukum', 'vera levelllllllllllll best shankar sir ur legend', 'h raja refer kandupudichavangalam like pannunga', 'massssss thalivaa vera level energi petta parak', 'nadakkadhu nadakkakoodathu nadakka vidamattaen expect line', 'nerkonda parvai continu day teater block buster movi ye like comment', 'r sijle energi solut pvt ltd r sijle com r r emi avail r chennai', 'hello youtub trent button softwar death ah', 'ultim star ajith kumar thala thala thala', 'unmaiya thala fana irrutha like poduga', 'thalaiva superstar rajinikanth number one mass hero', 'makkal selvan fan hit like',

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=1000)
X=cv.fit_transform(corpus).toarray()
y=data.iloc[:,-1].values
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
len(X[0])

1000

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [20]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [39]:
 y_pred=classifier.predict(X_test)
 print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]